#!/usr/bin/env python3
"""Generate strings_ui.xml for EN and ID locales."""
from pathlib import Path

# (name, english, indonesian)
PAIRS = [
    ("symbol_em_dash", "—", "—"),
    ("symbol_ellipsis", "…", "…"),
    ("action_clear", "Clear", "Hapus"),
    ("action_delete", "Delete", "Hapus"),
    ("action_approve", "Approve", "Setujui"),
    ("action_reject", "Reject", "Tolak"),
    ("action_logout", "Logout", "Keluar"),
    ("action_save_changes", "Save changes", "Simpan perubahan"),
    ("action_loading", "Loading…", "Memuat…"),
    ("action_load_more", "Load more", "Muat lebih banyak"),
    ("action_add_to_line", "Add to line…", "Tambah ke baris…"),
    ("action_remove_scan", "Remove scan", "Hapus pemindaian"),
    ("action_adjust_stock", "Adjust stock", "Sesuaikan stok"),
    ("action_relocate_bin", "Relocate to another bin", "Pindahkan ke bin lain"),
    ("action_save_link_tag", "Save & link tag", "Simpan & tautkan tag"),
    ("action_turn_on_bluetooth", "Turn on", "Nyalakan"),
    ("action_refresh_length", "Refresh length", "Segarkan panjang"),
    ("action_refresh_qty", "Refresh qty", "Segarkan jumlah"),
    ("action_refresh_source_stock", "Refresh source stock", "Segarkan stok sumber"),
    ("cd_back", "Back", "Kembali"),
    ("cd_clear", "Clear", "Hapus"),
    ("cd_choose", "Choose", "Pilih"),
    ("cd_search", "Search", "Cari"),
    ("cd_toggle_sort_direction", "Toggle sort direction", "Alihkan arah urutan"),
    ("cd_add_location", "Add location", "Tambah lokasi"),
    ("cd_new_adjustment", "New adjustment", "Penyesuaian baru"),
    ("cd_new_relocation", "New relocation", "Relokasi baru"),
    ("cd_phone_pairing_barcode", "Phone pairing barcode", "Barcode pemasangan ponsel"),
    ("cd_refresh_analytics", "Refresh analytics", "Segarkan analitik"),
    ("status_online", "Online", "Daring"),
    ("status_offline", "Offline", "Luring"),
    ("status_pairing", "Pairing…", "Memasangkan…"),
    ("status_active", "Active", "Aktif"),
    ("status_inactive", "Inactive", "Tidak aktif"),
    ("status_writing", "Writing…", "Menulis…"),
    ("status_ok", "OK", "OK"),
    ("label_product", "Product", "Produk"),
    ("label_variation", "Variation", "Variasi"),
    ("label_warehouse", "Warehouse", "Gudang"),
    ("label_location", "Location", "Lokasi"),
    ("label_epc", "EPC", "EPC"),
    ("label_barcode", "Barcode", "Barcode"),
    ("label_sku", "SKU", "SKU"),
    ("label_status", "Status", "Status"),
    ("label_type", "Type", "Tipe"),
    ("label_notes", "Notes", "Catatan"),
    ("label_reason", "Reason", "Alasan"),
    ("label_date", "Date", "Tanggal"),
    ("label_details", "Details", "Detail"),
    ("label_address", "Address", "Alamat"),
    ("label_phone", "Phone", "Telepon"),
    ("label_email", "Email", "Email"),
    ("label_capacity", "Capacity", "Kapasitas"),
    ("label_description", "Description", "Deskripsi"),
    ("label_manager", "Manager", "Manajer"),
    ("label_name", "Name", "Nama"),
    ("label_quantity", "Quantity", "Jumlah"),
    ("label_batch", "Batch", "Batch"),
    ("label_on_hand", "On hand", "Tersedia"),
    ("label_roll_number", "Roll number", "Nomor roll"),
    ("label_roll_number_short", "Roll #", "Roll #"),
    ("label_business_unit", "Business unit", "Unit bisnis"),
    ("label_zone", "Zone", "Zona"),
    ("label_zone_code", "Zone code", "Kode zona"),
    ("label_zone_name", "Zone name", "Nama zona"),
    ("label_aisle", "Aisle", "Lorong"),
    ("label_rack", "Rack", "Rak"),
    ("label_shelf", "Shelf", "Rak tingkat"),
    ("label_bin", "Bin", "Bin"),
    ("label_location_type", "Location type", "Tipe lokasi"),
    ("label_active", "Active", "Aktif"),
    ("label_from_location", "From location", "Dari lokasi"),
    ("label_to_location", "To location", "Ke lokasi"),
    ("label_adjustment_type", "Adjustment type", "Tipe penyesuaian"),
    ("label_current_qty", "Current qty", "Jumlah saat ini"),
    ("label_new_length", "New length", "Panjang baru"),
    ("label_new_qty_target", "New qty (target)", "Jumlah baru (target)"),
    ("label_unmarked_location", "Unmarked location", "Lokasi tanpa tanda"),
    ("label_code_value", "Code: %1$s", "Kode: %1$s"),
    ("label_type_value", "Type: %1$s", "Tipe: %1$s"),
    ("label_reason_value", "Reason: %1$s", "Alasan: %1$s"),
    ("label_date_value", "Date: %1$s", "Tanggal: %1$s"),
    ("label_from_value", "From: %1$s", "Dari: %1$s"),
    ("label_to_value", "To: %1$s", "Ke: %1$s"),
    ("label_from_unmarked", "From: Unmarked location", "Dari: Lokasi tanpa tanda"),
    ("label_to_unmarked", "To: Unmarked location", "Ke: Lokasi tanpa tanda"),
    ("label_roll_value", "Roll %1$s", "Roll %1$s"),
    ("label_batch_value", "Batch %1$s", "Batch %1$s"),
    ("label_length_value", "Length: %1$s", "Panjang: %1$s"),
    ("label_qty_value", "Qty: %1$s", "Jml: %1$s"),
    ("label_city_state_country", "City / state / country", "Kota / provinsi / negara"),
    ("label_nominal", "Nominal", "Nominal"),
    ("label_fill", "Fill", "Isi"),
    ("label_location_barcode", "Location barcode", "Barcode lokasi"),
    ("label_product_type", "Product type", "Tipe produk"),
    ("label_on_hand_length", "On-hand length", "Panjang tersedia"),
    ("label_nominal_length", "Nominal length", "Panjang nominal"),
    ("label_roll_status", "Roll status", "Status roll"),
    ("label_quantity_on_hand", "Quantity on hand", "Jumlah tersedia"),
    ("label_stock_type", "Stock type", "Tipe stok"),
    ("label_unit_price", "Unit price", "Harga satuan"),
    ("label_last_updated", "Last updated", "Terakhir diperbarui"),
    ("label_stock_line_id", "Stock line ID", "ID baris stok"),
    ("label_option", "Option", "Opsi"),
    ("label_batch_optional", "Batch (optional)", "Batch (opsional)"),
    ("label_available_at_source", "Available at source", "Tersedia di sumber"),
    ("label_length_to_move", "Length to move", "Panjang yang dipindahkan"),
    ("label_length_to_move_with_unit", "Length to move (%1$s)", "Panjang yang dipindahkan (%1$s)"),
    ("label_quantity_to_move", "Quantity to move", "Jumlah yang dipindahkan"),
    ("label_new_length_with_unit", "New length (%1$s)", "Panjang baru (%1$s)"),
    ("col_number", "Number", "Nomor"),
    ("col_reason", "Reason", "Alasan"),
    ("table_col_code", "Code", "Kode"),
    ("table_col_erp", "ERP", "ERP"),
    ("table_col_type", "Type", "Tipe"),
    ("table_col_erp_match", "ERP / match", "ERP / cocok"),
    ("scan_type_rfid", "RFID", "RFID"),
    ("scan_type_barcode", "Barcode", "Barcode"),
    ("placeholder_choose_product", "Choose product", "Pilih produk"),
    ("placeholder_choose_variation", "Choose variation", "Pilih variasi"),
    ("placeholder_choose_variation_optional", "Choose variation (optional)", "Pilih variasi (opsional)"),
    ("placeholder_no_variations", "No variations", "Tidak ada variasi"),
    ("placeholder_choose_warehouse", "Choose warehouse", "Pilih gudang"),
    ("placeholder_optional_location", "Optional location", "Lokasi opsional"),
    ("placeholder_source_bin", "Source bin (or unmarked)", "Bin sumber (atau tanpa tanda)"),
    ("placeholder_destination_bin", "Destination bin", "Bin tujuan"),
    ("placeholder_type", "Type", "Tipe"),
    ("search_hint", "Search…", "Cari…"),
    ("search_list_hint", "Search list…", "Cari daftar…"),
    ("search_product_hint", "Search product…", "Cari produk…"),
    ("filter_variations_hint", "Filter variations…", "Filter variasi…"),
    ("picker_no_matches", "No matches", "Tidak ada yang cocok"),
    ("display_empty", "—", "—"),
    ("time_ago_just_now", "just now", "baru saja"),
    ("time_ago_seconds", "%1$ds ago", "%1$dd lalu"),
    ("time_ago_minutes", "%1$dm ago", "%1$dm lalu"),
    ("home_title", "Dashboard", "Dasbor"),
    ("home_greeting", "Hello, %1$s", "Halo, %1$s"),
    ("home_greeting_fallback_name", "Operator", "Operator"),
    ("home_header_subtitle", "Warehouse RFID — live queue & device status", "RFID gudang — antrian langsung & status perangkat"),
    ("home_reader_label", "Reader", "Pembaca"),
    ("home_device_label", "Device", "Perangkat"),
    ("home_connect_rfd90", "Connect RFD90", "Hubungkan RFD90"),
    ("home_workflows_title", "Warehouse workflows", "Alur kerja gudang"),
    ("home_workflows_subtitle", "Receive, putaway, pick, count, encode", "Terima, penempatan, ambil, hitung, enkode"),
    ("home_sync_title", "RFID read sync", "Sinkronisasi baca RFID"),
    ("home_sync_idle", "Scans upload automatically; no manual sync needed", "Pemindaian diunggah otomatis; tidak perlu sinkron manual"),
    ("operations_title", "Work", "Kerja"),
    ("operations_subtitle", "Warehouse RFID workflows", "Alur kerja RFID gudang"),
    ("op_goods_receipt_title", "Goods receipt", "Penerimaan barang"),
    ("op_goods_receipt_desc", "Match tags to PO lines", "Cocokkan tag dengan baris PO"),
    ("op_putaway_title", "Putaway", "Penempatan"),
    ("op_putaway_desc", "Assign tags to locations", "Tetapkan tag ke lokasi"),
    ("op_pick_title", "Pick list", "Daftar ambil"),
    ("op_pick_desc", "Pick, pack & cut", "Ambil, kemas & potong"),
    ("op_cycle_count_title", "Stock opname", "Stok opname"),
    ("op_cycle_count_desc", "Count & approve ongoing", "Hitung & setujui yang berjalan"),
    ("op_rfid_session_title", "RFID location count", "Hitung lokasi RFID"),
    ("op_rfid_session_desc", "Scan all tags at a bin", "Pindai semua tag di bin"),
    ("op_encode_desc", "Write new EPC to label", "Tulis EPC baru ke label"),
    ("op_locate_desc", "Find tag in warehouse", "Temukan tag di gudang"),
    ("op_inventory_desc", "Warehouses, locations & stock", "Gudang, lokasi & stok"),
    ("connect_title", "RFID Reader", "Pembaca RFID"),
    ("connect_subtitle", "Zebra RFD90 Scan-to-Connect", "Zebra RFD90 Scan-to-Connect"),
    ("connect_status_connected", "Connected to %1$s", "Terhubung ke %1$s"),
    ("connect_reader_default_name", "RFD90", "RFD90"),
    ("connect_status_pairing", "Pairing with reader…", "Memasangkan dengan pembaca…"),
    ("connect_status_idle", "Pair using Scan-to-Connect — saved readers reconnect automatically.", "Pasangkan dengan Scan-to-Connect — pembaca tersimpan terhubung otomatis."),
    ("connect_tab_scan_reader", "Scan reader QR", "Pindai QR pembaca"),
    ("connect_tab_phone_barcode", "Show phone barcode", "Tampilkan barcode ponsel"),
    ("connect_hardware_title", "Hardware controls", "Kontrol perangkat keras"),
    ("connect_hardware_top_trigger", "Top trigger — press and hold to start RFID scan; release to stop.", "Pemicu atas — tekan dan tahan untuk memulai pemindaian RFID; lepas untuk berhenti."),
    ("connect_hardware_bottom_trigger", "Bottom trigger — press to start continuous barcode scan; press again to stop.", "Pemicu bawah — tekan untuk memulai pemindaian barcode berkelanjutan; tekan lagi untuk berhenti."),
    ("connect_disconnect", "Disconnect reader", "Putuskan pembaca"),
    ("connect_scan_reader_title", "Scan the QR / barcode on your RFD90", "Pindai QR / barcode di RFD90 Anda"),
    ("connect_scan_reader_body", "Recommended — no phone Bluetooth address needed. On the reader, open Scan-to-Connect and scan its barcode with this camera.", "Disarankan — tidak perlu alamat Bluetooth ponsel. Di pembaca, buka Scan-to-Connect dan pindai barcodenya dengan kamera ini."),
    ("connect_phone_barcode_title", "Let the RFD90 scan this phone", "Biarkan RFD90 memindai ponsel ini"),
    ("connect_bt_permission_required", "Allow Nearby devices / Bluetooth permission so the app can read this phone address automatically.", "Izinkan perangkat terdekat / Bluetooth agar aplikasi dapat membaca alamat ponsel secara otomatis."),
    ("connect_mac_auto_detected", "Bluetooth address detected automatically.", "Alamat Bluetooth terdeteksi otomatis."),
    ("connect_show_barcode_hint", "Show this barcode to the RFD90 Scan-to-Connect scanner.", "Tunjukkan barcode ini ke pemindai Scan-to-Connect RFD90."),
    ("connect_mac_saved", "Using saved Bluetooth address from a previous pairing.", "Menggunakan alamat Bluetooth tersimpan dari pemasangan sebelumnya."),
    ("connect_retry_auto_detect", "Try auto-detect again", "Coba deteksi otomatis lagi"),
    ("connect_mac_auto_failed_body", "Android blocks most apps from reading the phone Bluetooth address. Use the Scan reader QR tab when possible, or enter the address manually below.", "Android memblokir sebagian besar aplikasi membaca alamat Bluetooth ponsel. Gunakan tab Pindai QR pembaca jika memungkinkan, atau masukkan alamat secara manual di bawah."),
    ("connect_mac_detecting", "Detecting this phone's Bluetooth address…", "Mendeteksi alamat Bluetooth ponsel ini…"),
    ("connect_retry_auto_detect_short", "Retry auto-detect", "Coba deteksi otomatis"),
    ("connect_enter_mac_manually", "Enter address manually", "Masukkan alamat secara manual"),
    ("connect_phone_mac_label", "Phone Bluetooth address", "Alamat Bluetooth ponsel"),
    ("connect_phone_mac_placeholder", "A1B2C3D4E5F6", "A1B2C3D4E5F6"),
    ("connect_save_mac", "Save address", "Simpan alamat"),
    ("connect_reader_scanned_connect", "Reader scanned — connect now", "Pembaca dipindai — hubungkan sekarang"),
    ("connect_tip_use_qr_tab", "Tip: open Connect → Scan reader QR — that flow never needs your phone address.", "Tips: buka Hubungkan → Pindai QR pembaca — alur itu tidak memerlukan alamat ponsel."),
    ("search_title", "Search", "Cari"),
    ("search_subtitle", "Scan RFID or barcode — unknown tags can be registered", "Pindai RFID atau barcode — tag tidak dikenal dapat didaftarkan"),
    ("search_connect_required", "Connect an RFD90 on the Connect tab to start scanning.", "Hubungkan RFD90 di tab Hubungkan untuk mulai memindai."),
    ("search_scan_hint", "Hold top trigger for RFID. Release to stop.", "Tahan pemicu atas untuk RFID. Lepas untuk berhenti."),
    ("search_empty", "No tags yet — scan to populate this table.", "Belum ada tag — pindai untuk mengisi tabel ini."),
    ("search_col_code", "Code", "Kode"),
    ("search_col_erp", "ERP", "ERP"),
    ("search_col_type", "Type", "Tipe"),
    ("search_col_seen", "Seen", "Terlihat"),
    ("search_error_lookup_failed", "Lookup failed", "Pencarian gagal"),
    ("search_error_not_registered", "Not registered", "Tidak terdaftar"),
    ("search_tag_details_title", "Tag details", "Detail tag"),
    ("search_register_tag", "Register this tag", "Daftarkan tag ini"),
    ("search_adjust_stock", "Adjust stock", "Sesuaikan stok"),
    ("search_relocate_bin", "Relocate to another bin", "Pindahkan ke bin lain"),
    ("workspace_select_title", "Select workspace", "Pilih ruang kerja"),
    ("workspace_no_business_unit_admin", "No business unit assigned to this account. Contact your administrator.", "Tidak ada unit bisnis yang ditetapkan untuk akun ini. Hubungi administrator Anda."),
    ("workspace_header_title", "Where are you working?", "Di mana Anda bekerja?"),
    ("workspace_header_subtitle", "Choose business unit, then warehouse — team is set automatically", "Pilih unit bisnis, lalu gudang — tim ditetapkan otomatis"),
    ("workspace_select_bu_first", "Select a business unit first", "Pilih unit bisnis terlebih dahulu"),
    ("workspace_no_warehouses", "No warehouses assigned for this business unit.", "Tidak ada gudang yang ditetapkan untuk unit bisnis ini."),
    ("workspace_no_team_mapped", "%1$s has no team mapped. Contact your administrator.", "%1$s tidak memiliki tim yang dipetakan. Hubungi administrator Anda."),
    ("workspace_bu_warehouse_count_zero", "No warehouses", "Tidak ada gudang"),
    ("workspace_bu_warehouse_count_one", "1 warehouse", "1 gudang"),
    ("workspace_current_unit", "Current unit", "Unit saat ini"),
    ("workspace_current_warehouse", "Current warehouse", "Gudang saat ini"),
    ("encode_title", "Encode tag", "Enkode tag"),
    ("encode_subtitle", "Choose product → request EPC → write → verify → confirm", "Pilih produk → minta EPC → tulis → verifikasi → konfirmasi"),
    ("encode_connect_required", "Connect the RFD90 reader before encoding.", "Hubungkan pembaca RFD90 sebelum enkode."),
    ("encode_warehouse_required", "Select a workspace warehouse (Home or Settings) before encoding.", "Pilih gudang ruang kerja (Beranda atau Pengaturan) sebelum enkode."),
    ("encode_product_identity", "Product identity", "Identitas produk"),
    ("encode_step_request_epc", "1. Request EPC from server", "1. Minta EPC dari server"),
    ("encode_error_choose_product", "Choose a product", "Pilih produk"),
    ("encode_error_empty_epc", "Server returned empty EPC", "Server mengembalikan EPC kosong"),
    ("encode_epc_summary", "EPC to write: %1$s", "EPC untuk ditulis: %1$s"),
    ("encode_epc_summary_roll", " · Roll %1$s", " · Roll %1$s"),
    ("encode_target_epc", "Target EPC", "EPC target"),
    ("encode_step_pick_blank", "2. Use latest scan as blank tag", "2. Gunakan pemindaian terbaru sebagai tag kosong"),
    ("encode_step_reselect_blank", "Reselect blank tag from scan", "Pilih ulang tag kosong dari pemindaian"),
    ("encode_error_scan_blank_first", "Hold trigger and scan the blank tag first.", "Tahan pemicu dan pindai tag kosong terlebih dahulu."),
    ("encode_source_tag_ready", "Source tag: %1$s — tap Write EPC to program.", "Tag sumber: %1$s — ketuk Tulis EPC untuk memprogram."),
    ("encode_step_write", "3. Write EPC to tag on device", "3. Tulis EPC ke tag di perangkat"),
    ("encode_write_success", "Written %1$s. Scan again to verify, then confirm.", "Ditulis %1$s. Pindai lagi untuk verifikasi, lalu konfirmasi."),
    ("encode_col_scanned_epc", "Scanned EPC", "EPC terpindai"),
    ("encode_col_match", "Match", "Cocok"),
    ("encode_scan_after_write_empty", "Hold trigger to scan tags after writing.", "Tahan pemicu untuk memindai tag setelah menulis."),
    ("encode_step_confirm", "4. Confirm encode on server", "4. Konfirmasi enkode di server"),
    ("encode_error_request_first", "Request EPC first", "Minta EPC terlebih dahulu"),
    ("encode_success_encoded", "Encoded", "Terkode"),
    ("encode_write_epc", "Write EPC", "Tulis EPC"),
    ("encode_confirm_encode", "Confirm encode", "Konfirmasi enkode"),
    ("variation_fallback_title", "Variation #%1$d", "Variasi #%1$d"),
    ("product_fallback_title", "Product #%1$d", "Produk #%1$d"),
    ("label_roll_length_optional", "Roll length (optional)", "Panjang roll (opsional)"),
    ("label_batch_number_optional", "Batch number (optional)", "Nomor batch (opsional)"),
    ("label_expiry_date_optional", "Expiry date (optional, YYYY-MM-DD)", "Tanggal kedaluwarsa (opsional, YYYY-MM-DD)"),
    ("symbol_unknown", "?", "?"),
    ("locate_title", "Locate item", "Lokasi item"),
    ("locate_subtitle", "Identify a tag, then sweep until green", "Identifikasi tag, lalu sapu hingga hijau"),
    ("locate_error_choose_product", "Choose a product first", "Pilih produk terlebih dahulu"),
    ("error_empty_response", "Empty response", "Respons kosong"),
    ("error_empty_warehouse", "Empty warehouse", "Gudang kosong"),
    ("error_empty_location", "Empty location", "Lokasi kosong"),
    ("error_no_warehouse_in_workspace", "No warehouse selected in workspace", "Tidak ada gudang dipilih di ruang kerja"),
    ("label_length", "Length", "Panjang"),
    ("locate_error_no_tags", "No registered tags for this product", "Tidak ada tag terdaftar untuk produk ini"),
    ("locate_connect_required", "Connect an RFD90 on the Connect tab first.", "Hubungkan RFD90 di tab Hubungkan terlebih dahulu."),
    ("locate_profile_dense", "RF profile: Dense (Settings)", "Profil RF: Padat (Pengaturan)"),
    ("locate_profile_range", "RF profile: Range (Settings)", "Profil RF: Jangkauan (Pengaturan)"),
    ("locate_epc_filter_target", " · EPC filter on target", " · Filter EPC pada target"),
    ("locate_epc_filter_prefix", " · EPC prefix filter", " · Filter awalan EPC"),
    ("locate_tab_scan_first", "Scan first", "Pindai dulu"),
    ("locate_tab_by_product", "By product", "Berdasarkan produk"),
    ("locate_scan_first_hint", "Hold top trigger to read nearby tags, then tap a row to pick which EPC to locate.", "Tahan pemicu atas untuk membaca tag terdekat, lalu ketuk baris untuk memilih EPC yang dilokasi."),
    ("locate_empty_scan", "Hold top trigger to scan tags in front of you.", "Tahan pemicu atas untuk memindai tag di depan Anda."),
    ("locate_find_tags", "Find registered tags", "Temukan tag terdaftar"),
    ("locate_registered_tags_header", "Registered tags — tap to locate", "Tag terdaftar — ketuk untuk melokasi"),
    ("locate_manual_epc_label", "Or enter EPC directly", "Atau masukkan EPC langsung"),
    ("locate_status_locating", "Locating", "Melokasi"),
    ("locate_sweep_hint", "Hold top trigger and sweep · release to stop · green = closer", "Tahan pemicu atas dan sapu · lepas untuk berhenti · hijau = lebih dekat"),
    ("locate_select_tag_hint", "Select or scan a tag above, then hold top trigger to locate it.", "Pilih atau pindai tag di atas, lalu tahan pemicu atas untuk melokasinya."),
    ("locate_col_epc", "EPC", "EPC"),
    ("locate_col_item", "Item", "Item"),
    ("locate_col_rssi", "RSSI", "RSSI"),
    ("cycle_count_title", "Cycle count", "Hitung siklus"),
    ("cycle_count_subtitle", "Inventory all tags at a location", "Inventarisasi semua tag di lokasi"),
    ("cycle_count_label_location", "Storage location (optional)", "Lokasi penyimpanan (opsional)"),
    ("cycle_count_btn_start_session", "Start session", "Mulai sesi"),
    ("cycle_count_col_epc", "EPC", "EPC"),
    ("cycle_count_col_rssi", "RSSI", "RSSI"),
    ("cycle_count_empty_tags", "Scan tags for this count session.", "Pindai tag untuk sesi hitung ini."),
    ("cycle_count_btn_submit", "Submit count", "Kirim hitungan"),
    ("cycle_count_success_session_started", "Session started", "Sesi dimulai"),
    ("cycle_count_error_start_session_first", "Start a session first", "Mulai sesi terlebih dahulu"),
    ("cycle_count_success_submitted", "Submitted", "Terkirim"),
    ("inventory_title", "Inventory", "Inventaris"),
    ("inventory_subtitle", "Master data & on-hand stock", "Data master & stok tersedia"),
    ("inventory_perm_adjust_denied", "You do not have permission to create stock adjustments.", "Anda tidak memiliki izin untuk membuat penyesuaian stok."),
    ("inventory_perm_relocate_denied", "You do not have permission to create stock relocations.", "Anda tidak memiliki izin untuk membuat relokasi stok."),
    ("inventory_hub_warehouse_title", "Warehouse", "Gudang"),
    ("inventory_hub_warehouse_desc", "Your current workspace warehouse", "Gudang ruang kerja Anda saat ini"),
    ("inventory_hub_locations_title", "Locations", "Lokasi"),
    ("inventory_hub_locations_desc", "Bins, racks & zones per warehouse", "Bin, rak & zona per gudang"),
    ("inventory_hub_stock_title", "Stock by location", "Stok per lokasi"),
    ("inventory_hub_stock_desc", "View on-hand qty at each bin", "Lihat jumlah tersedia di setiap bin"),
    ("inventory_hub_adjustments_title", "Stock adjustments", "Penyesuaian stok"),
    ("inventory_hub_adjustments_desc", "Fix wrong quantities on the floor", "Perbaiki jumlah salah di lantai"),
    ("inventory_hub_relocations_title", "Stock relocations", "Relokasi stok"),
    ("inventory_hub_relocations_desc", "Move stock between bins", "Pindahkan stok antar bin"),
    ("inventory_no_warehouse_selected", "No warehouse selected. Choose a workspace from Home or Settings.", "Tidak ada gudang dipilih. Pilih ruang kerja dari Beranda atau Pengaturan."),
    ("inventory_current_workspace", "Current workspace", "Ruang kerja saat ini"),
    ("inventory_warehouse_not_found", "Warehouse not found.", "Gudang tidak ditemukan."),
    ("inventory_warehouse_web_managed_note", "Warehouse master data is managed on the web ERP. This device shows your assigned workspace only.", "Data master gudang dikelola di ERP web. Perangkat ini hanya menampilkan ruang kerja yang ditetapkan."),
    ("inventory_locations_title", "Locations", "Lokasi"),
    ("inventory_workspace_warehouse", "Workspace warehouse", "Gudang ruang kerja"),
    ("search_locations_hint", "Search locations…", "Cari lokasi…"),
    ("inventory_locations_empty", "No locations yet.", "Belum ada lokasi."),
    ("inventory_location_new_title", "New location", "Lokasi baru"),
    ("inventory_location_edit_title", "Edit location", "Edit lokasi"),
    ("inventory_location_create", "Create location", "Buat lokasi"),
    ("inventory_location_delete_title", "Delete location?", "Hapus lokasi?"),
    ("inventory_location_delete_message", "Locations with stock movements cannot be deleted.", "Lokasi dengan pergerakan stok tidak dapat dihapus."),
    ("location_type_storage", "Storage", "Penyimpanan"),
    ("location_type_receiving", "Receiving", "Penerimaan"),
    ("location_type_picking", "Picking", "Pengambilan"),
    ("location_type_shipping", "Shipping", "Pengiriman"),
    ("location_type_quality", "Quality", "Kualitas"),
    ("inventory_stock_picker_title", "Stock by location", "Stok per lokasi"),
    ("inventory_stock_picker_subtitle", "Pick a bin to view stock", "Pilih bin untuk melihat stok"),
    ("inventory_stock_no_bins", "No bin locations found.", "Tidak ada lokasi bin ditemukan."),
    ("inventory_on_hand_subtitle", "On-hand stock", "Stok tersedia"),
    ("search_stock_hint", "Search product, SKU, variation, roll…", "Cari produk, SKU, variasi, roll…"),
    ("inventory_unmarked_empty", "No unlocated stock in this warehouse.", "Tidak ada stok tanpa lokasi di gudang ini."),
    ("inventory_location_empty", "No stock at this location.", "Tidak ada stok di lokasi ini."),
    ("inventory_adjustments_title", "Adjustments", "Penyesuaian"),
    ("inventory_adjustments_subtitle", "Pending & recent", "Tertunda & terbaru"),
    ("search_adjustments_hint", "Search adjustments…", "Cari penyesuaian…"),
    ("inventory_adjustments_empty", "No adjustments yet.", "Belum ada penyesuaian."),
    ("inventory_workspace_required", "Select a workspace warehouse first.", "Pilih gudang ruang kerja terlebih dahulu."),
    ("inventory_adjustment_default_reason", "Mobile stock correction", "Koreksi stok mobile"),
    ("inventory_adjustment_submit", "Submit adjustment", "Kirim penyesuaian"),
    ("error_select_variation_for_stock", "Select a variation to load stock.", "Pilih variasi untuk memuat stok."),
    ("error_select_variation_for_product", "Select a variation for this product.", "Pilih variasi untuk produk ini."),
    ("error_enter_roll_number", "Enter the roll number for this roll product.", "Masukkan nomor roll untuk produk roll ini."),
    ("error_new_length_must_differ", "New length must differ from current.", "Panjang baru harus berbeda dari saat ini."),
    ("error_new_qty_must_differ", "New quantity must differ from current.", "Jumlah baru harus berbeda dari saat ini."),
    ("inventory_created_pending_approval", "Created pending approval: %1$s", "Dibuat menunggu persetujuan: %1$s"),
    ("inventory_adjustment_fallback_title", "Adjustment", "Penyesuaian"),
    ("inventory_length_change", "Length change: %1$s", "Perubahan panjang: %1$s"),
    ("inventory_qty_change", "Qty change: %1$s", "Perubahan jumlah: %1$s"),
    ("adjustment_type_correction", "Correction", "Koreksi"),
    ("adjustment_type_loss", "Loss", "Kehilangan"),
    ("adjustment_type_damage", "Damage", "Kerusakan"),
    ("adjustment_type_expiry", "Expiry", "Kedaluwarsa"),
    ("adjustment_type_theft", "Theft", "Pencurian"),
    ("adjustment_type_other", "Other", "Lainnya"),
    ("inventory_relocations_title", "Relocations", "Relokasi"),
    ("inventory_relocations_subtitle", "Move stock between bins", "Pindahkan stok antar bin"),
    ("search_relocations_hint", "Search relocations…", "Cari relokasi…"),
    ("inventory_relocations_empty", "No relocations yet.", "Belum ada relokasi."),
    ("relocation_form_title", "Relocate stock", "Pindahkan stok"),
    ("relocation_form_subtitle", "Same warehouse · different bin", "Gudang sama · bin berbeda"),
    ("relocation_default_reason", "Mobile bin relocation", "Relokasi bin mobile"),
    ("relocation_submit", "Submit relocation", "Kirim relokasi"),
    ("error_select_variation_for_source_stock", "Select a variation to load source stock.", "Pilih variasi untuk memuat stok sumber."),
    ("error_enter_roll_number_relocate", "Enter the roll number to relocate.", "Masukkan nomor roll untuk dipindahkan."),
    ("error_qty_must_be_positive", "Enter a quantity greater than zero.", "Masukkan jumlah lebih dari nol."),
    ("error_from_to_must_differ", "From and to locations must be different.", "Lokasi asal dan tujuan harus berbeda."),
    ("error_unmarked_destination_required", "Choose a destination bin different from unmarked source.", "Pilih bin tujuan berbeda dari sumber tanpa tanda."),
    ("relocation_fallback_title", "Relocation", "Relokasi"),
    ("relocation_approve_and_move", "Approve & move stock", "Setujui & pindahkan stok"),
    ("bluetooth_off_title", "Bluetooth is off", "Bluetooth mati"),
    ("bluetooth_off_body_compact", "Turn on Bluetooth to pair and use the RFD90 reader.", "Nyalakan Bluetooth untuk memasangkan dan menggunakan pembaca RFD90."),
    ("bluetooth_off_body_full", "Turn on Bluetooth to pair the Zebra RFD90, scan tags, and sync warehouse workflows.", "Nyalakan Bluetooth untuk memasangkan Zebra RFD90, memindai tag, dan menyinkronkan alur kerja gudang."),
    ("reader_default_name", "RFD90", "RFD90"),
    ("reader_serial_label", "Reader serial (S/N)", "Serial pembaca (S/N)"),
    ("reader_serial_not_reported", "Not reported by reader yet", "Belum dilaporkan oleh pembaca"),
    ("reader_bluetooth_name", "Bluetooth name: %1$s", "Nama Bluetooth: %1$s"),
    ("reader_serial_help", "On the back label: S/N is for identification and support. Configure sled Wi-Fi with 123RFID Desktop if needed.", "Pada label belakang: S/N untuk identifikasi dan dukungan. Konfigurasi Wi-Fi sled dengan 123RFID Desktop jika diperlukan."),
    ("firmware_progress_min", "0%", "0%"),
    ("firmware_progress_max", "100%", "100%"),
    ("firmware_phase_idle", "Idle", "Siaga"),
    ("firmware_phase_checking", "Checking", "Memeriksa"),
    ("firmware_phase_up_to_date", "Up to date", "Terbaru"),
    ("firmware_phase_update_available", "Update available", "Pembaruan tersedia"),
    ("firmware_phase_ready_to_install", "Ready to install", "Siap dipasang"),
    ("firmware_phase_downloading", "Downloading", "Mengunduh"),
    ("firmware_phase_installing", "Installing", "Memasang"),
    ("firmware_phase_success", "Success", "Berhasil"),
    ("firmware_phase_failed", "Failed", "Gagal"),
    ("sync_pending_count", "%1$d pending", "%1$d tertunda"),
    ("sync_status_synced", "Synced", "Tersinkron"),
    ("sync_all_synced", "All scans synced", "Semua pemindaian tersinkron"),
    ("list_load_error", "Failed to load list", "Gagal memuat daftar"),
    ("list_refresh_error", "Failed to refresh list", "Gagal menyegarkan daftar"),
    ("list_synced_ago", "Synced %1$s", "Tersinkron %1$s"),
    ("list_showing_partial", "Showing %1$d of %2$d — load more or refine search", "Menampilkan %1$d dari %2$d — muat lebih banyak atau perbaiki pencarian"),
    ("list_sort_by", "Sort: %1$s", "Urutkan: %1$s"),
    ("home_analytics_load_error", "Could not load analytics", "Tidak dapat memuat analitik"),
    ("home_work_queue_title", "Work queue", "Antrian kerja"),
    ("home_updated_ago", "Updated %1$s", "Diperbarui %1$s"),
    ("home_metric_putaway", "Putaway", "Penempatan"),
    ("home_metric_putaway_hint", "open tasks", "tugas terbuka"),
    ("home_metric_pick_lists", "Pick lists", "Daftar ambil"),
    ("home_metric_pick_hint", "to pick", "untuk diambil"),
    ("home_metric_opname", "Stock opname", "Stok opname"),
    ("home_metric_opname_hint", "counting", "menghitung"),
    ("home_metric_receipts", "Receipts", "Penerimaan"),
    ("home_metric_receipts_hint", "pending / partial", "tertunda / sebagian"),
    ("home_session_title", "Session", "Sesi"),
    ("reader_status_online", "Reader online", "Pembaca daring"),
    ("reader_status_offline", "Reader offline", "Pembaca luring"),
    ("home_total_open_tasks", "Total open warehouse tasks", "Total tugas gudang terbuka"),
    ("scan_unknown_erp_hint_map", "%1$d not in ERP — tap red row to map", "%1$d tidak ada di ERP — ketuk baris merah untuk memetakan"),
    ("scan_unmatched_lines_hint", "%1$d not on lines — tap yellow to add or remove", "%1$d tidak di baris — ketuk kuning untuk tambah atau hapus"),
    ("scan_trigger_hint_dual", "Top trigger = RFID · bottom trigger or field = barcode (same table)", "Pemicu atas = RFID · pemicu bawah atau kolom = barcode (tabel sama)"),
    ("scan_roll_products_hint", "Roll products: one tag per roll — scan confirms the roll; enter length manually.", "Produk roll: satu tag per roll — pemindaian mengonfirmasi roll; masukkan panjang secara manual."),
    ("scan_table_empty_line_match", "Scanned tags appear here — green = matched, yellow = wrong line, red = unknown.", "Tag terpindai muncul di sini — hijau = cocok, kuning = baris salah, merah = tidak dikenal."),
    ("dialog_product_not_on_lines_title", "Product not on lines", "Produk tidak di baris"),
    ("dialog_product_not_on_lines_body", "Add this scan to a line anyway, or remove it from the session.", "Tambahkan pemindaian ini ke baris, atau hapus dari sesi."),
    ("dialog_choose_line_title", "Choose line", "Pilih baris"),
    ("workflow_line_fallback", "Line %1$s", "Baris %1$s"),
    ("roll_label", "Roll %1$s", "Roll %1$s"),
    ("scan_status_not_registered_map", "Not registered — tap to map", "Tidak terdaftar — ketuk untuk memetakan"),
    ("scan_status_no_matching_line", "No matching line", "Tidak ada baris yang cocok"),
    ("scan_status_matched", "Matched", "Cocok"),
    ("scan_matched_line_arrow", "→ %1$s", "→ %1$s"),
    ("scan_enter_length_manually", "Enter length manually", "Masukkan panjang secara manual"),
    ("scan_unknown_erp_hint_register", "%1$d not in ERP — tap red row to register", "%1$d tidak ada di ERP — ketuk baris merah untuk mendaftar"),
    ("scan_trigger_hint_hold", "Hold top trigger to scan", "Tahan pemicu atas untuk memindai"),
    ("scan_table_empty", "Scanned tags appear here.", "Tag terpindai muncul di sini."),
    ("scan_status_not_registered", "Not registered", "Tidak terdaftar"),
    ("scan_status_linked", "Linked", "Tertaut"),
    ("tag_register_title", "Register tag", "Daftarkan tag"),
    ("tag_register_body", "This code is not in ERP yet. Link it to a product so workflows can use it.", "Kode ini belum ada di ERP. Tautkan ke produk agar alur kerja dapat menggunakannya."),
    ("tag_register_product_placeholder", "Search product name or SKU", "Cari nama produk atau SKU"),
    ("tag_register_variation_placeholder", "Choose variation / descriptors", "Pilih variasi / deskriptor"),
    ("tag_register_search_name_sku_hint", "Search name or SKU…", "Cari nama atau SKU…"),
    ("error_choose_product", "Choose a product", "Pilih produk"),
    ("error_choose_variation", "Choose a variation for this product", "Pilih variasi untuk produk ini"),
    ("location_unmarked_subtitle", "Stock in warehouse but not assigned to a bin", "Stok di gudang tetapi tidak ditetapkan ke bin"),
    ("location_no_bin", "No bin", "Tanpa bin"),
    ("location_zone_code", "Zone %1$s", "Zona %1$s"),
    ("product_type_roll", "Roll", "Roll"),
    ("product_type_standard", "Standard", "Standar"),
    ("roll_number_pill", "Roll #%1$s", "Roll #%1$s"),
    ("batch_pill", "Batch %1$s", "Batch %1$s"),
    ("stock_roll_on_hand_nominal", "%1$s on hand · nominal %2$s", "%1$s tersedia · nominal %2$s"),
    ("stock_on_hand", "%1$s on hand", "%1$s tersedia"),
    ("roll_full_description", "Full roll — remaining length matches nominal", "Roll penuh — panjang tersisa sesuai nominal"),
    ("roll_partial_description", "Partial roll — cut or consumed length", "Roll sebagian — panjang dipotong atau dikonsumsi"),
    ("stock_on_hand_label", "On hand: %1$s", "Tersedia: %1$s"),
    ("location_stock_detail_title", "Product & stock", "Produk & stok"),
    ("roll_status_full", "Full roll", "Roll penuh"),
    ("roll_status_partial", "Partial roll", "Roll sebagian"),
    ("location_stock_no_permission", "You do not have permission to adjust or relocate stock.", "Anda tidak memiliki izin untuk menyesuaikan atau memindahkan stok."),
    ("stock_line_id_value", "#%1$d", "#%1$d"),
    ("tag_info_section_product", "Product", "Produk"),
    ("tag_info_section_variation", "Variation", "Variasi"),
    ("tag_info_section_stock", "Stock", "Stok"),
    ("tag_info_section_location", "Location", "Lokasi"),
    ("tag_info_section_label", "Label", "Label"),
    ("tag_info_section_tag", "Tag", "Tag"),
    ("common_error_scan_tags_first", "Scan tags first", "Pindai tag terlebih dahulu"),
    ("common_success_confirmed", "Confirmed", "Dikonfirmasi"),
    ("common_col_product", "Product", "Produk"),
    ("common_col_variation", "Var", "Var"),
    ("common_col_roll", "Roll", "Roll"),
    ("common_col_status", "Status", "Status"),
    ("putaway_title", "Putaway", "Penempatan"),
    ("putaway_subtitle_list", "Tap a task · auto-syncs", "Ketuk tugas · sinkron otomatis"),
    ("putaway_empty_list", "No putaway tasks.", "Tidak ada tugas penempatan."),
    ("putaway_search_placeholder", "Search tasks…", "Cari tugas…"),
    ("putaway_col_task", "Task", "Tugas"),
    ("putaway_col_gr", "GR", "GR"),
    ("putaway_col_to_put", "To put", "Untuk ditempatkan"),
    ("putaway_col_put", "Put", "Tempatkan"),
    ("putaway_empty_items", "No items on this task.", "Tidak ada item pada tugas ini."),
    ("putaway_label_qty_putaway", "Qty putaway", "Jml penempatan"),
    ("putaway_label_putaway_length", "Putaway length", "Panjang penempatan"),
    ("putaway_line_roll_marker", "(roll)", "(roll)"),
    ("putaway_line_roll_suffix", " · roll %1$s", " · roll %1$s"),
    ("putaway_label_storage_location", "Storage location", "Lokasi penyimpanan"),
    ("putaway_fallback_location", "Location #%1$d", "Lokasi #%1$d"),
    ("putaway_placeholder_location", "Choose location", "Pilih lokasi"),
    ("putaway_label_rfid_location", "RFID confirm location", "Konfirmasi lokasi RFID"),
    ("putaway_placeholder_rfid_location", "Choose location for scan confirm", "Pilih lokasi untuk konfirmasi pemindaian"),
    ("putaway_btn_rfid_confirm", "RFID confirm at location", "Konfirmasi RFID di lokasi"),
    ("putaway_btn_save", "Save", "Simpan"),
    ("putaway_btn_complete", "Complete", "Selesai"),
    ("putaway_picker_search_location", "Search zone, aisle, rack…", "Cari zona, lorong, rak…"),
    ("putaway_picker_search_rfid_location", "Search location…", "Cari lokasi…"),
    ("putaway_success_saved", "Putaway saved", "Penempatan disimpan"),
    ("putaway_success_completed", "Putaway completed", "Penempatan selesai"),
    ("putaway_error_empty_task", "Empty task", "Tugas kosong"),
    ("putaway_task_locked_message", "Task is %1$s — open from the list only while pending or in progress.", "Tugas %1$s — buka dari daftar hanya saat tertunda atau berjalan."),
    ("pick_title", "Pick list", "Daftar ambil"),
    ("pick_subtitle_list", "Tap a row · auto-syncs", "Ketuk baris · sinkron otomatis"),
    ("pick_empty_list", "No pick lists.", "Tidak ada daftar ambil."),
    ("pick_search_placeholder", "Search pick lists…", "Cari daftar ambil…"),
    ("pick_col_number", "Pick #", "Ambil #"),
    ("pick_col_requested", "Req", "Diminta"),
    ("pick_col_picked", "Picked", "Diambil"),
    ("pick_empty_lines", "No pick lines.", "Tidak ada baris ambil."),
    ("pick_label_picked_qty", "Picked qty", "Jml diambil"),
    ("pick_label_picked_length", "Picked length", "Panjang diambil"),
    ("pick_field_label_product", "%1$s — %2$s", "%1$s — %2$s"),
    ("pick_line_roll_suffix", " · roll %1$s", " · roll %1$s"),
    ("pick_btn_sync_picks", "Sync picks to server", "Sinkronkan ambil ke server"),
    ("pick_btn_save_picking", "Save picking", "Simpan pengambilan"),
    ("pick_btn_complete_picking", "Complete picking", "Selesaikan pengambilan"),
    ("pick_tab_pick", "Pick", "Ambil"),
    ("pick_tab_pack_cut", "Pack & cut", "Kemas & potong"),
    ("pick_section_container_packing", "Container packing", "Pengemasan kontainer"),
    ("pick_col_assignment", "Assignment", "Penugasan"),
    ("pick_col_packed", "Packed", "Dikemas"),
    ("pick_empty_container_lines", "No container lines.", "Tidak ada baris kontainer."),
    ("pick_label_packed_container", "Packed — %1$s", "Dikemas — %1$s"),
    ("pick_col_pack_cut", "Pack/Cut", "Kemas/Potong"),
    ("pick_pack_cut_container", "container", "kontainer"),
    ("pick_empty_pack_lines", "No lines.", "Tidak ada baris."),
    ("pick_label_cut_lengths", "Cut lengths (%1$s) — %2$s", "Panjang potong (%1$s) — %2$s"),
    ("pick_cut_lengths_hint", "Enter one or more lengths separated by commas (e.g. 2.5, 1.0). Total must match requested.", "Masukkan satu atau lebih panjang dipisahkan koma (mis. 2.5, 1.0). Total harus sesuai permintaan."),
    ("pick_label_packed_qty", "Packed qty — %1$s", "Jml dikemas — %1$s"),
    ("pick_btn_save_pack_cut", "Save pack & cut", "Simpan kemas & potong"),
    ("pick_fallback_container", "Container", "Kontainer"),
    ("pick_fallback_product", "Product", "Produk"),
    ("pick_success_picking_saved", "Picking saved", "Pengambilan disimpan"),
    ("pick_success_picking_completed", "Picking completed", "Pengambilan selesai"),
    ("pick_success_pack_cut_saved", "Pack & cut saved", "Kemas & potong disimpan"),
    ("pick_error_empty_pick_list", "Empty pick list", "Daftar ambil kosong"),
    ("opname_title_list", "Stock opname", "Stok opname"),
    ("opname_title_create", "New stock opname", "Stok opname baru"),
    ("opname_title_count_fallback", "Stock count", "Hitung stok"),
    ("opname_subtitle_list", "Draft & ongoing counts", "Draf & hitungan berjalan"),
    ("opname_subtitle_create", "Schedule a count for your warehouse", "Jadwalkan hitungan untuk gudang Anda"),
    ("opname_btn_new", "New opname", "Opname baru"),
    ("opname_empty_list", "No stock opnames yet. Tap New opname to start.", "Belum ada stok opname. Ketuk Opname baru untuk memulai."),
    ("opname_search_placeholder", "Search opnames…", "Cari opname…"),
    ("opname_col_number", "Opname #", "Opname #"),
    ("opname_col_type", "Type", "Tipe"),
    ("opname_label_warehouse", "Warehouse: %1$s", "Gudang: %1$s"),
    ("opname_label_type", "Type (full, partial, cycle_count)", "Tipe (full, partial, cycle_count)"),
    ("opname_label_notes", "Notes (optional)", "Catatan (opsional)"),
    ("opname_btn_create_start", "Create & start counting", "Buat & mulai menghitung"),
    ("opname_col_location", "Loc", "Lok"),
    ("opname_col_system", "Sys", "Sis"),
    ("opname_col_counted", "Cnt", "Hit"),
    ("opname_col_variance", "Δ", "Δ"),
    ("opname_empty_lines", "No stock lines in snapshot.", "Tidak ada baris stok dalam snapshot."),
    ("opname_label_counted_qty", "Counted qty", "Jml dihitung"),
    ("opname_label_counted_length", "Counted length", "Panjang dihitung"),
    ("opname_field_label_product", "%1$s — %2$s", "%1$s — %2$s"),
    ("opname_line_roll_suffix", " · roll %1$s", " · roll %1$s"),
    ("opname_btn_save_counts", "Save counts", "Simpan hitungan"),
    ("opname_btn_done_counting", "Done counting", "Selesai menghitung"),
    ("opname_btn_approve", "Approve & adjust stock", "Setujui & sesuaikan stok"),
    ("opname_success_counts_saved", "Counts saved", "Hitungan disimpan"),
    ("opname_success_marked_complete", "Marked complete — ready to approve", "Ditandai selesai — siap disetujui"),
    ("opname_success_approved", "Stock opname approved", "Stok opname disetujui"),
    ("opname_error_empty_response", "Empty opname response", "Respons opname kosong"),
    ("opname_error_missing_id", "Missing opname id", "ID opname hilang"),
    ("opname_error_empty_check", "Empty check", "Pemeriksaan kosong"),
    ("opname_error_empty_opname", "Empty opname", "Opname kosong"),
    ("gr_title_list", "Goods receipt", "Penerimaan barang"),
    ("gr_title_create", "New goods receipt", "Penerimaan barang baru"),
    ("gr_subtitle_list", "Tap a row to open · auto-syncs", "Ketuk baris untuk membuka · sinkron otomatis"),
    ("gr_subtitle_create", "Receipt info → items to receive", "Info penerimaan → item yang diterima"),
    ("gr_btn_new_receipt", "New receipt", "Penerimaan baru"),
    ("gr_empty_list", "No goods receipts found.", "Tidak ada penerimaan barang ditemukan."),
    ("gr_search_placeholder", "Search receipts…", "Cari penerimaan…"),
    ("gr_col_gr_number", "GR #", "GR #"),
    ("gr_col_warehouse", "Warehouse", "Gudang"),
    ("gr_col_date", "Date", "Tanggal"),
    ("gr_tab_receipt_info", "Receipt info", "Info penerimaan"),
    ("gr_tab_items_count", "Items (%1$d)", "Item (%1$d)"),
    ("gr_section_receive_from", "Receive from", "Terima dari"),
    ("gr_section_receive_from_subtitle", "Choose source type and document", "Pilih tipe sumber dan dokumen"),
    ("gr_label_source_document", "Source document", "Dokumen sumber"),
    ("gr_source_type_po_title", "Purchase order", "Pesanan pembelian"),
    ("gr_source_type_po_description", "Receive stock from a supplier PO", "Terima stok dari PO pemasok"),
    ("gr_source_type_po_picker_placeholder", "Search open purchase orders", "Cari pesanan pembelian terbuka"),
    ("gr_source_type_transfer_title", "Stock transfer", "Transfer stok"),
    ("gr_source_type_transfer_description", "Inbound from another warehouse", "Masuk dari gudang lain"),
    ("gr_source_type_transfer_picker_placeholder", "Search transfers ready to receive", "Cari transfer siap diterima"),
    ("gr_source_type_return_title", "Sales return", "Retur penjualan"),
    ("gr_source_type_return_description", "Customer return documents", "Dokumen retur pelanggan"),
    ("gr_source_type_return_picker_placeholder", "Search sales returns", "Cari retur penjualan"),
    ("gr_source_loading_lines", "Loading line items…", "Memuat baris item…"),
    ("gr_cd_clear_source", "Clear source", "Hapus sumber"),
    ("gr_section_receipt_details", "Receipt details", "Detail penerimaan"),
    ("gr_section_receipt_details_subtitle_create", "Warehouse, date & delivery info", "Gudang, tanggal & info pengiriman"),
    ("gr_section_receipt_details_subtitle_edit", "Edit delivery info before putaway completes", "Edit info pengiriman sebelum penempatan selesai"),
    ("gr_placeholder_warehouse", "Choose warehouse", "Pilih gudang"),
    ("gr_label_receipt_date", "Receipt date", "Tanggal penerimaan"),
    ("gr_label_delivery_note", "Delivery note #", "Nota pengiriman #"),
    ("gr_label_vehicle_number", "Vehicle number", "Nomor kendaraan"),
    ("gr_label_driver_name", "Driver name", "Nama pengemudi"),
    ("gr_label_received_by", "Received by", "Diterima oleh"),
    ("gr_placeholder_receiver", "Choose receiver", "Pilih penerima"),
    ("gr_label_receipt_notes", "Receipt notes", "Catatan penerimaan"),
    ("gr_readonly_warehouse", "Warehouse: %1$s", "Gudang: %1$s"),
    ("gr_col_ordered", "Ord", "Pesan"),
    ("gr_col_previously_received", "Prev", "Sblm"),
    ("gr_col_remaining", "Rem", "Sisa"),
    ("gr_col_accepted", "Acc", "Terima"),
    ("gr_col_rejected", "Rej", "Tolak"),
    ("gr_empty_lines_loading", "Loading lines…", "Memuat baris…"),
    ("gr_empty_lines_no_source", "Choose a source on Receipt info to load lines.", "Pilih sumber di Info penerimaan untuk memuat baris."),
    ("gr_empty_lines_detail", "No line items.", "Tidak ada baris item."),
    ("gr_label_accepted", "Accepted", "Diterima"),
    ("gr_label_accepted_length", "Accepted length", "Panjang diterima"),
    ("gr_label_rejected", "Rejected", "Ditolak"),
    ("gr_label_rejected_length", "Rejected length", "Panjang ditolak"),
    ("gr_line_roll_suffix", " · roll %1$s", " · roll %1$s"),
    ("gr_line_hint_suffix", " · hint %1$s", " · petunjuk %1$s"),
    ("gr_detail_source_summary", "Source: %1$s #%2$d · %3$s", "Sumber: %1$s #%2$d · %3$s"),
    ("gr_putaway_fallback_label", "Putaway #%1$d", "Penempatan #%1$d"),
    ("gr_btn_open_putaway", "Open %1$s", "Buka %1$s"),
    ("gr_no_putaway_hint", "No putaway task yet — only approved accepted qty creates putaway.", "Belum ada tugas penempatan — hanya jumlah diterima yang disetujui membuat penempatan."),
    ("gr_readonly_date_warehouse", "Date: %1$s · WH: %2$s", "Tanggal: %1$s · GD: %2$s"),
    ("gr_readonly_delivery_note", "Delivery note: %1$s", "Nota pengiriman: %1$s"),
    ("gr_readonly_vehicle", "Vehicle: %1$s", "Kendaraan: %1$s"),
    ("gr_readonly_driver", "Driver: %1$s", "Pengemudi: %1$s"),
    ("gr_readonly_received_by", "Received by: %1$s", "Diterima oleh: %1$s"),
    ("gr_readonly_notes", "Notes: %1$s", "Catatan: %1$s"),
    ("gr_locked_message", "Receipt is locked — quantities cannot be edited.", "Penerimaan terkunci — jumlah tidak dapat diedit."),
    ("gr_btn_save_receipt", "Save goods receipt", "Simpan penerimaan barang"),
    ("gr_btn_sync_scans", "Sync scans to server", "Sinkronkan pemindaian ke server"),
    ("gr_picker_search_source", "Search source…", "Cari sumber…"),
    ("gr_picker_search_warehouse", "Search warehouse…", "Cari gudang…"),
    ("gr_picker_search_user", "Search user…", "Cari pengguna…"),
    ("gr_fallback_product_name", "Product", "Produk"),
    ("gr_fallback_user_name", "User #%1$d", "Pengguna #%1$d"),
    ("gr_fallback_current_user", "Me", "Saya"),
    ("gr_fallback_warehouse_name", "Warehouse", "Gudang"),
    ("gr_error_load_receipt", "Could not load receipt", "Tidak dapat memuat penerimaan"),
    ("gr_error_no_remaining_lines", "No remaining lines on this source", "Tidak ada baris tersisa pada sumber ini"),
    ("gr_error_failed_load_lines", "Failed to load lines", "Gagal memuat baris"),
    ("gr_error_choose_source", "Choose a source document", "Pilih dokumen sumber"),
    ("gr_error_choose_warehouse", "Choose a warehouse", "Pilih gudang"),
    ("gr_error_choose_receiver", "Choose who received this", "Pilih siapa yang menerima ini"),
    ("gr_error_enter_roll_length", "Enter measured length for %1$s", "Masukkan panjang terukur untuk %1$s"),
    ("gr_error_enter_qty", "Enter accepted or rejected qty for %1$s", "Masukkan jumlah diterima atau ditolak untuk %1$s"),
    ("gr_error_receipt_not_loaded", "Receipt not loaded", "Penerimaan tidak dimuat"),
    ("gr_success_saved", "Goods receipt saved", "Penerimaan barang disimpan"),
    ("gr_success_saved_with_putaway", "Goods receipt saved · Putaway %1$s created", "Penerimaan barang disimpan · Penempatan %1$s dibuat"),
    ("gr_success_matched", "Matched", "Cocok"),
    ("gr_error_created_empty", "Created but empty response", "Dibuat tetapi respons kosong"),
    ("gr_error_created_no_id", "Created but no ID returned", "Dibuat tetapi tidak ada ID dikembalikan"),
    ("workspace_bu_warehouse_count_other", "%1$d warehouses", "%1$d gudang"),
    ("new_adjustment_title", "New adjustment", "Penyesuaian baru"),
]

PLURALS = [
    ("scan_count", "%1$d scan", "%1$d scans", "%1$d pemindaian", "%1$d pemindaian"),
    ("home_sync_pending", "%1$d read batch queued — uploading when online", "%1$d read batches queued — uploading when online", "%1$d batch baca antre — diunggah saat daring", "%1$d batch baca antre — diunggah saat daring"),
    ("search_unique_count", "%1$d unique scan", "%1$d unique scans", "%1$d pemindaian unik", "%1$d pemindaian unik"),
    ("locate_tags_found", "%1$d tag found — tap one to locate", "%1$d tags found — tap one to locate", "%1$d tag ditemukan — ketuk untuk melokasi", "%1$d tag ditemukan — ketuk untuk melokasi"),
    ("locate_scan_count", "%1$d scan", "%1$d scans", "%1$d pemindaian", "%1$d pemindaian"),
    ("sync_scans_waiting", "%1$d scan waiting to sync", "%1$d scans waiting to sync", "%1$d pemindaian menunggu sinkron", "%1$d pemindaian menunggu sinkron"),
    ("list_item_count", "%1$d item", "%1$d items", "%1$d item", "%1$d item"),
    ("location_line_count", "%1$d line", "%1$d lines", "%1$d baris", "%1$d baris"),
    ("gr_source_lines_ready", "%1$d line ready — open Items tab to receive", "%1$d lines ready — open Items tab to receive", "%1$d baris siap — buka tab Item untuk menerima", "%1$d baris siap — buka tab Item untuk menerima"),
]


def esc(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("'", "\\'")
        .replace('"', "&quot;")
    )


def write_xml(path: Path, lang: int) -> None:
    lines = ['<?xml version="1.0" encoding="utf-8"?>', "<resources>"]
    for name, en, id_ in PAIRS:
        val = (en, id_)[lang]
        lines.append(f'    <string name="{name}">{esc(val)}</string>')
    for pname, one_en, other_en, one_id, other_id in PLURALS:
        lines.append(f'    <plurals name="{pname}">')
        if lang == 0:
            lines.append(f'        <item quantity="one">{esc(one_en)}</item>')
            lines.append(f'        <item quantity="other">{esc(other_en)}</item>')
        else:
            lines.append(f'        <item quantity="one">{esc(one_id)}</item>')
            lines.append(f'        <item quantity="other">{esc(other_id)}</item>')
        lines.append("    </plurals>")
    lines.append("</resources>")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    write_xml(root / "app/src/main/res/values/strings_ui.xml", 0)
    write_xml(root / "app/src/main/res/values-in/strings_ui.xml", 1)
    print(f"Wrote {len(PAIRS)} strings + {len(PLURALS)} plurals")
